language: node_js
node_js:
- '7'
sudo: required
services:
  - docker
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - CLOUDFRONT_DISTRIBUTION_ID: EJ8WZKA0CXU9V
jobs:
  include:
    - stage: Deploy Prod
      script: npm run examples
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: tw.radar
        acl: public_read
        skip_cleanup: true
        local_dir: dist
        on:
          repo: thoughtworks/build-your-own-radar
          branch: release
    - stage: Push to DockerHub
      before_install:
        - sudo apt-get update
        - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - export REPO=wwwthoughtworks/build-your-own-radar
        - export TAG=latest
        - docker build -f Dockerfile -t $REPO:$COMMIT .
        - docker tag $REPO:$COMMIT $REPO:$TAG
        - docker push $REPO
    - stage: Invalidate CDN
      install: pip install --user awscli && export PATH=$PATH:$HOME/.local/bin
      script: 'aws configure set preview.cloudfront true && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"'